services:
  openlit:
    image: ghcr.io/openlit/openlit:latest
    container_name: openlit
    environment:
      TELEMETRY_ENABLED: "true"
      INIT_DB_HOST: ${INIT_DB_HOST}
      INIT_DB_PORT: ${INIT_DB_PORT}
      INIT_DB_DATABASE: ${INIT_DB_DATABASE:-openlit}
      INIT_DB_USERNAME: ${INIT_DB_USERNAME:-default}
      INIT_DB_PASSWORD: ${INIT_DB_PASSWORD}
      SQLITE_DATABASE_URL: file:/app/client/data/data.db
      PORT: ${PORT:-3000}
      DOCKER_PORT: ${PORT:-3000}
      # OAuth Environment Variables
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID:-}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET:-}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID:-}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET:-}

    env_file:
      - path: .env
        required: false
    ports:
      - "${PORT:-3000}:${DOCKER_PORT:-3000}"
    volumes:
      - openlit-data:/app/client/data
    restart: always

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.94.0
    container_name: otel-collector
    environment:
      OTEL_DB_HOST: ${OTEL_DB_HOST}
      OTEL_DB_PORT: ${OTEL_DB_PORT}
      INIT_DB_DATABASE: ${INIT_DB_DATABASE:-openlit}
      INIT_DB_USERNAME: ${INIT_DB_USERNAME:-default}
      INIT_DB_PASSWORD: ${INIT_DB_PASSWORD}
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8888:8888"
      - "55679:55679"
    volumes:
      - ./assets/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    restart: always

volumes:
  openlit-data:
