receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 100

exporters:
  logging:
    loglevel: info
  
  # Use HTTP exporter instead of ClickHouse exporter
  otlphttp:
    endpoint: https://v5s7ohqrt5.us-east-1.aws.clickhouse.cloud:8443
    headers:
      authorization: "Basic ZGVmYXVsdDpIWnFObDJIfmRwbDV4"  # base64 encoded default:HZqNl2H~dpl5x

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlphttp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlphttp]
