receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  memory_limiter:
    limit_mib: 512

extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

exporters:
  # Use logging exporter for debugging
  logging:
    loglevel: debug
    sampling_initial: 5
    sampling_thereafter: 200
  
  # ClickHouse exporter - simplified configuration
  clickhouse:
    endpoint: https://${env:OTEL_DB_HOST}:9440/
    database: ${env:INIT_DB_DATABASE}
    username: ${env:INIT_DB_USERNAME}
    password: ${env:INIT_DB_PASSWORD}
    timeout: 10s
    traces_table_name: otel_traces
    metrics_table_name: otel_metrics
    logs_table_name: otel_logs

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [logging, clickhouse]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [logging, clickhouse]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [logging, clickhouse]
